# Bungeemode adds BungeeCord support for HeavySpleef
# !!! IMPORTANT NOTICE: If using this add-on, make sure       !!!
# !!! to set settings -> late-bind to true in your spigot.yml !!!
# !!! otherwise HeavySpleef may not be able to handle joins   !!!
# !!! when the plugin has been loaded yet                     !!!
#
# Also: If you want to use the spectate:autospectate flag for the game
#       make sure to use the bungee optimized flag for it instead (bungee-autospectate)

# Specify wether bungeemode is enabled on this server or not
enabled: false

# If bungeemode is enabled you have to choose 
# a game the player will join once he joins the server
#
# This should be the name of the game created by /spleef create
game: Spleef

# When this is enabled, the server's motd changes to the
# current status of the game. If you intend to change the motds
# please open your language file under i18n/locale_COUNTRY_LANG.yml
use-motd: true

# Wether players are able to spectate the game when it's already ingame
spectate-when-ingame: true

# Specifies at which game phase the player should be sent back
# Valid values:
# - finish -> Sends back players when the game has finished.
#             If you choose this option, make sure to enable
#             the spectate flag and the spectate:bungee-autospectate flag.
# - lose -> Players are sent back to the server once they lose in Spleef
#           (Note that they will not see the winner then)
send-back-on: finish

# Specify the name of the server where players are sent back
# once they meet the above criteria
send-back-to: lobby

# Wether the server should restart when the spleef game ends
# This requires to setup a Spigot restart script otherwise
# the server will just shutdown
restart: true

# This sets the countdown after how many seconds players are sent back
# to the lobby server after the game ends and the server restarts
# if configured above
restart-countdown: 15

# Do not change this unless you want this config to be resetted
config-version: 2